language: python

sudo: false

matrix:
  include:
    # Python 2.7
    - env: ENV_FILE="travis/27-latest-conda-forge.yml"

    # Python 3.5 and 3.6 test all supported Pandas versions
    - env: ENV_FILE="travis/35-defaults.yml"
    - env: ENV_FILE="travis/35-latest-conda-forge.yml"
    - env: ENV_FILE="travis/36-defaults.yml"
    - env: ENV_FILE="travis/36-latest-conda-forge.yml"

    # Python 3.7
    - env: ENV_FILE="travis/37-defaults.yml"
    - env: ENV_FILE="travis/37-latest-conda-forge.yml"

    # Python 3.8
    - env: ENV_FILE="travis/38-defaults.yml"
    - env: ENV_FILE="travis/38-latest-conda-forge.yml"

install:
  # Install conda
  - source travis/install.sh
  - conda update -n base conda
  - conda install -n base conda-libmamba-solver
  - conda config --set solver libmamba
  - conda env create --file="${ENV_FILE}"
  - conda init bash
  - source activate test
  - pip install -e .
  - conda list

script:
  - pytest

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
  - codecov
  - coveralls